name: Doxygen
if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: "./doxyfile"
        working-directory: "."

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html
